CREATE TABLE IF NOT EXISTS stats
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app               VARCHAR(255)                            NOT NULL,
    uri               VARCHAR(255)                            NOT NULL,
    ip                VARCHAR(32)                             NOT NULL,
    request_date_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_stats PRIMARY KEY (id)
);